name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu:latest", "archlinux:latest"]
    container:
      image: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          if [ "${{ matrix.os }}" = "ubuntu:latest" ]; then
            apt-get update
            apt-get install -y zsh git curl build-essential autoconf libncurses-dev
          elif [ "${{ matrix.os }}" = "archlinux:latest" ]; then
            pacman -Syu --noconfirm
            pacman -S --noconfirm zsh base-devel git
          fi

      - name: Test completion
        run: cd test && zsh -f runtests.zsh fzftab.ztst

      - name: Build binary module
        run: zsh -fc 'source ./fzf-tab.zsh && build-fzf-tab-module'

      - name: Test binary module
        run: cd test && zsh -f runtests.zsh fzftab.ztst
